### ISSUE TITLE
Bug on `scss/dependencies/core.scss`

### ISSUE THREAD

**Issue by 3den** [salesforce-ux/design-system#173]
I have installed slds with bower and I and getting an error `Invalid CSS after "": expected selector, was ""
` when it is included.

```scss
// application.scss
@import "salesforce-lightning-design-system/scss/index";
// the @import above throws => Invalid CSS after "": expected selector, was ""
```

The error is on `scss/dependencies/core.scss:24`.

```scss
@mixin core($scoped: null, $globals: null) {
  @if $scoped == 'scoped' {
    $scoped-selector: '&';
    $scoped-root:     $scoped-selector;
    $scoped-body:     '&:not(html), body';
  }

  $scoped-selector: '' !default;
  $scoped-root:     'html' !default;
  $scoped-body:     'body' !default;

  // This will throw and error because it will try to create a style with no selector...
  // the fix is to skip this code instead of creating a bogus selector  
  #{$scoped-selector} {
    ...
  }
  ...
}
```
