### ISSUE TITLE
checkbox label size

### ISSUE THREAD

**Issue by matejp84** [salesforce-ux/design-system#179]
Is there any particular reason that in this CSS:

``` css
.slds .slds-radio .slds-form-element__label {
  display: inline;
  vertical-align: middle;
  font-size: 14px;
}
```

font-size is set to 14px and everywhere else 12px? It looks kinda strange having checkbox labels a little bigger than others.
