### ISSUE TITLE
Styles for HTML 5 form validation.

### ISSUE THREAD

**Issue by 3den** [salesforce-ux/design-system#182]
Currently the forms look good and we have styles for errors but unfortunately the only way to add those styles is by change the parent class by hand... HTML 5 supports form validation and is very easy to take advantage of that by doing something like:

``` scss
.slds-input {
   ... 
   & + .slds-form-element__help { display: none; }

   &:invalid:focus {
       // whatever code we have for ".slds-has-error .slds-input", mabe we can just @extend that...
        & + .slds-form-element__help { display: block; }
   } 
}
```

In that case the markup would be pretty similar and also compatible to what we currently have:

``` html
<div class="slds-form-element slds-has-validation">
    <label class="slds-form-element__label" for="email-input-01">
      <abbr class="slds-required" title="required">*</abbr> Input Label
    </label>
    <div class="slds-form-element__control">
      <input id="email-input-01" class="slds-input" type="email" placeholder="Email" required>
      <div class="slds-form-element__help">Please enter a valid email</div>
    </div>
</div>
```
