### ISSUE TITLE
@font-face does not work with Rails

### ISSUE THREAD

**Issue by 3den** [salesforce-ux/design-system#211]
I noticed that you guys added the $static-font-path, $static-image-path, and $static-icon-path variables but unfortunately the `@mixin font-face` provided by SLDS does not work for Rails apps because the asset pipeline digest adds a "fingerprint" to all files that it compiles.  e.g.

```
salesforce-lightning-design-system/assets/icons/utility-sprite/svg/symbols-74eeb1d5dcdf25d778c74314aca07a0092247d5f0f56f0b0a4b64bfd026acbd6.svg
```

Trying to load Failed to load something like`salesforce-lightning-design-system/assets/fonts/webfonts/SalesforceSans-Regular.woff`will raise an error "resource: the server responded with a status of 404 (Not Found)".

This is issue makes `salesforce-lightning-design-system/scss/index` incompatible with apps built on Rails. 

Below I am suggesting some solutions for this problem:

1. Just publish lightning in some public CDN would should this problem very easly and make lightning much more accessible (https://github.com/salesforce-ux/design-system/issues/169). 
2. Give variables where we can set the full path to the files instead of just the base directory.
3. Add compass and refactor the `scss/dependencies/_typography.scss` to be something like: https://gist.github.com/3den/bc29de4c4a623fd8f0dcfdcb490dc97a

**Comment by kaelig** [comment]
Thank you for raising this!

Would it be possible for you to build a test case (for example on c9.io) where we could troubleshoot it and adapt SLDS to support the Rails asset pipeline?

Another option would be to have a trigger for enabling/disabling the font face mixin. This way, developers could load fonts the way they want and it would solve edge cases like this. Thoughts?

**Comment by 3den** [comment]
@kaelig thanks for the feedback, I will build a test case an post it here.

Disabling the SLDS code that sets the font-face is what I have being doing, by not importing those files, but that is a hack, developers should not need to reinvent pieces of the SLDS. Also doing that would not that solve the problem for `icons` and `images`.

I think it would be ok to have variables that can be set when needed tho:

```scss
# /scss/_config.scss
/// Font Path
///
/// @type String
$static-font-path: '../fonts/webfonts' !default;
$font-file: 'SalesforceSans' !default;

// Light
$static-font-light-path: '#{$static-font-path}#{$font-file}-Light' !default;
$static-font-light-woff2-path: '#{$static-font-light-path}.woff2' !default;
$static-font-light-woff-path: '#{$static-font-light-path}.woff' !default;

// LightItalic
$static-font-light-italic-path: '#{$static-font-path}#{$font-file}-LightItalic' !default;
$static-font-light-italic-woff2-path: '#{$static-font-light-italic-path}.woff2' !default;
$static-font-light-italic-woff-path: '#{$static-font-light-italic-path}.woff' !default;

// Regular
$static-font-light-regular-path: '#{$static-font-path}#{$font-file}-Regular' !default;
$static-font-light-regular-woff2-path: '#{$static-font-light-regular-path}.woff2' !default;
$static-font-light-regular-woff-path: '#{$static-font-light-regular-path}.woff' !default;
```

Those settings are very compostable would be easier to override.
