### ISSUE TITLE
Style rule conflicts with slds-is-selected

### ISSUE THREAD

**Issue by sdruckerfig** [salesforce-ux/design-system#320]
This style rule:

``` css
@media (max-width: 48em) {
  .slds-max-medium-table--stacked:not(.slds-no-row-hover) tbody tr:hover td,
  .slds-max-medium-table--stacked:not(.slds-no-row-hover) tbody tr:hover th {
    background-color: inherit!important;
    box-shadow: none!important;
  }
}
```

Effectively prevents the application of slds-is-selected to a tr tag as the background-color:inherit takes precedence.
