### ISSUE TITLE
Typo: Missing a . (class indicator) on a selector

### ISSUE THREAD

**Issue by jwilcurt-salesforce-com** [salesforce-ux/design-system#444]
Typo on:

* [Line `27` of `components/notifications/flavors/prompt/_index.scss`](https://github.com/salesforce-ux/design-system/blob/37e8312b3f3b17127d089afdb00e5bcdabfa2623/ui/components/notifications/flavors/prompt/_index.scss#L27)

It will produce this CSS:

```css
.slds-modal--prompt slds-modal__close {
  display: none;
}
```
