### ISSUE TITLE
Is there some information available regarding the structuring of the files?

### ISSUE THREAD

**Issue by StudioSpindle** [salesforce-ux/design-system#577]
Within the [backgrounds file](https://github.com/salesforce-ux/design-system/blob/master/design-tokens/extensions/ui-force/background-color.yml), you'll find both foreground and background definitions. 

For example: [at line 15](https://github.com/salesforce-ux/design-system/blob/73d9a9822c4a815170941fdc5a8500eb9e00f340/design-tokens/extensions/ui-force/background-color.yml#L15) `COLOR_FOREGROUND_PRIMARY:`. Is it on purpose that a foreground color has been defined in the background file? And if so, what is the logic?

I'm using the structure in a bit of a different way, and am wondering about what the best practices are regarding file/folder structure. 

How about a structure like the following example. Where there's a reoccurring pattern of each state and foreground/background. Or would something like this be too specific for web or something?

```
props:
  # BUTTONS
  ## PRIMARY
  ### REGULAR
  COLOR_FOREGROUND_BUTTON_PRIMARY:
      value: "white"
      comment: "Foreground button primary color."
  COLOR_BACKGROUND_BUTTON_PRIMARY:
    value: "blue"
    comment: "Button primary background color."
  ### HOVER
  COLOR_BACKGROUND_BUTTON_PRIMARY_HOVER:
    value: "darkblue"
    comment: "Button primary background color primary hover state."
  ### INVERTED
  COLOR_BACKGROUND_BUTTON_PRIMARY_INVERTED:
    value: "white"
    comment: "Button primary background color. Used on dark backgrounds. "
  COLOR_FOREGROUND_BUTTON_PRIMARY_INVERTED:
    value: "blue"
    comment: "Foreground button primary inverted color."
  ### ACTIVE
  COLOR_BACKGROUND_BUTTON_PRIMARY_ACTIVE:
    value: "cyan"
    comment: "Button primary background color active."  
  ### DISABLED
  COLOR_BACKGROUND_BUTTON_PRIMARY_DISABLED:
      value: "silver"
      comment: "Button primary disabled background color. Used for inactive buttons."
  ## SECONDARY
  ### REGULAR
  ### etc.
```
