### ISSUE TITLE
SLDS Path Blueprint Is Missing Background Color When for `current` elements which are not `active`

### ISSUE THREAD

**Issue by SethAngell** [salesforce-ux/design-system#774]
When using the [SLDS Path Blueprint](https://v1.lightningdesignsystem.com/components/path/#With-different-stage-selected), if you have a step which is current but not active, the color of the element beneath the path element shows through in the triangular portion on the right side. 

This can be hard to notice at first glance

![Image](https://github.com/user-attachments/assets/986e52c5-8bb8-4178-bfb4-cb95646227c9)

but by switching the background color it becomes apparent.

![Image](https://github.com/user-attachments/assets/72b473f6-c574-4ae2-a83f-63236bddbecd)

This stuck out to me, as I'm working on a new LWC with SLDS2 in mind, and noticed that the grey background is poking through

![Image](https://github.com/user-attachments/assets/ec65f38a-909e-4270-8ea5-910c67eb04a0)

**Comment by SethAngell** [comment]
If anyone else stumbles across this, the following (very hacky) css seems to resolve the issue for now.

```css
.slds-path__nav li:not(.slds-is-active).slds-is-current:first-child::before {
    background-color: var(--slds-g-color-surface-container-1);
    border-top-color: var(--slds-g-color-brand-base-30);
    border-top-width: 1px;
    border-top-style: solid;
}

.slds-path__nav li:not(.slds-is-active).slds-is-current:first-child::after {
    background-color: var(--slds-g-color-surface-container-1);
    border-bottom-color: var(--slds-g-color-brand-base-30);
    border-bottom-width: 1px;
    border-bottom-style: solid;
}

.slds-path__nav li.slds-is-active:hover:first-child::before,
.slds-path__nav li.slds-is-active:hover:first-child::after {
    background-image: none;
}



.slds-path__nav li:not(.slds-is-active).slds-is-current:hover:first-child::before {
    border-top-color: var(--slds-g-color-brand-base-20);
}

.slds-path__nav li:not(.slds-is-active).slds-is-current:hover:first-child::after {
    border-bottom-color: var(--slds-g-color-brand-base-20);
}

.slds-path__item::before {
    transform: skew(30deg) translate3d(0, 0, 0);
}
```
